### ISSUE TITLE
User info view

### ISSUE THREAD

**Issue by MurkyMeow** [MurkyMeow/lecture#10]
После авторизации в cookie клиента сохраняется зашифрованный id сесии.

Благодаря этому сервер может ассоциировать клиента с его аккаунтом.

Прекрасно! Но на фронтенде из кук невозможно достать информацию об аккунте (например, никнейм).

Поэтому нужно создать отдельный контроллер, который возвращает её.

Только чтобы он не присылал пароль, пожалуйста. Я думаю, достаточно ограничиться никнеймом и email .

**Comment by pCoLDq** [comment]
Added.
