### ISSUE TITLE
Вход в аккаунт не работает

### ISSUE THREAD

**Issue by MurkyMeow** [MurkyMeow/lecture#11]
Как сейчас в `SigninView` проверяется соотвествие пароля:

```python
if user.password == password:
  return credentials(request, user)
```

При этом `user.password` зашифрован, а `password` (который достаётся из запроса) &mdash; нет.

Это значит, что зайти в свой аккаунт невозможно, даже если указать верные данные.

Тесты проходят, потому что юзер создаётся через create:

```python
def setUp(self):
  User.objects.create(
    username=user['name'], email=user['email'], password=user['password']
  )
```

Это тоже нужно поправить.

**Comment by pCoLDq** [comment]
Fixed.
