### ISSUE TITLE
Синхронизация лекций с бд

### ISSUE THREAD

**Issue by MurkyMeow** [MurkyMeow/lecture#14]
Так как лекции не хранятся в бд, мы теряем автоматическую валидацию целостности. 

Например, комментарий можно оставить к несуществующей лекции.

Кроме того, id лекций не определяется автоматически и не присылается клиенту (без него оставить комментарий невозможно).

- [x] Переделать формат лекций, чтобы их можно было синхронизировать с бд
- [x] Написать алгоритм синхронизации

**Comment by pCoLDq** [comment]
### Вариант формата лекций.

1. Хранить данные о лекциях в бд(id, title, content).
2. Иметь 1 шаблон html, и при каждом вызове лекции заполнять его через JS и выдавать.
3. Как насчёт кеширования? Это решит проблему с небольшими задержками при постоянном вызове одной и той же лекции(если пользователь ищет наиболее подходящую для себя, например).

**Demo code:**

_views.py:_
`def LectureDataView(request):`
`    lecture = Lecture.objects.get(pk=request.data.get('lecture_id'))`
`    return Response( { 'title':  lecture.title, 'content': lecture.content } )`

**Comment by MurkyMeow** [comment]
~Вся проблема в том, что их нельзя хранить, как (id, title, content) &mdash; они содержат не только текст, но ещё картинки, анимации и интерактивные javascript вставки. Именно поэтому они пишутся в html файлах.~

Есть вариант сделать так: Lecture(id, file_path), но это лишь частично решает проблему &mdash; валидации слайдов всё ещё нет.

Тут 2 пути:

- не делить лекции на слайды

- делать по файлу на каждый слайд и хранить всё так:
Lecture(id, dir_path)
Slide(id, lecture_id, file_path)

При этом файловая структура будет выглядеть так:

```
├── courses
│   ├── Название курса
│   │   ├── Название лекции
│   │   │   ├── 1 слайд.html
│   │   │   ├── 2 слайд.html
│   │   ├── Название лекции
│   │   │   ├── 1 слайд.html
│   │   │   ├── 2 слайд.html
```

**Comment by pCoLDq** [comment]
2-й вариант.

**Comment by MurkyMeow** [comment]
Мне не нравится идея большого количества маленьких файлов=). Попробуем первое.

**Comment by MurkyMeow** [comment]
И так, каждый курс теперь хранится в отдельных js файлах, которые собираются в один json файл.

https://github.com/MurkyMeow/lecture-docs/blob/master/deploy.sh &mdash; скрипт, который

- склонирует репозиторий с курсами

- сгенерирует json файлы

- переместит их в нужную директорию:

Скачай его и запусти через git bash таким образом:

```sh
./deploy.sh C:/Users/murky_meow/Desktop/lecture/courses
```

Путь поменяй на свой. Обратие внимание, в bash используется __прямой__, а не обратный слеш.

Один курс будет выглядеть примерно так:

```js
// course.json

[
  {
    "title": "lecture_1_title",
    "subtitle": "lecture_1_subtitle",
    "background": "red",
    "slides": [
      {
        "title": "slide_1_title",
        "content": "slide_1_content"
      },
      {
        "title": "slide_2_title",
        "content": "slide_2_content"
      }
    ]
  },
  {
    "title": "lecture_2_title",
    "subtitle": "lecture_2_subtitle",
    "background": "red",
    "slides": [
      {
        "title": "slide_1_title",
        "content": "slide_1_content"
      },
      {
        "title": "slide_2_title",
        "content": "slide_2_content"
      }
    ]
  }
]
```

От тебя нужен скрипт, который при каждом запуске будет делать drop таблицы с курсами и заполнять всё заново на основе json файлов.

Понятно, как должны выглядеть модели, но я, на всякий случай, уточню:

### Course
- name

### Lecture
- course_id
- title
- subtitle
- background

### Slide
- lecture_id
- title
- content

И для пущей ясности приведу отрывок кода:

```python
# sync.py

from os import walk
import json

(_, _, filenames) = walk('./courses').next()

for filename in filenames:
  course = Course.objects.create(name=filename.replace('.json', ''))
  lectures = json.load(open(filename))
  for lecture in lectures:
    Lecture.objects.create(
      course=course,
      title=lecture['title'],
      .....
    )

**Comment by MurkyMeow** [comment]
Решено в #15.
